### ISSUE TITLE
exercices repos

### ISSUE THREAD

**Issue by joseteodoro** [joseteodoro/PUCES-JUN2020#8]

**Comment by fabiodealenca** [comment]
https://github.com/fabiodealenca/Design-Patterns-Exercices/
RA00272008

**Comment by vinimyls** [comment]
https://github.com/vinimyls/PUC-PostGraduate

**Comment by dkotsuka** [comment]
https://github.com/dkotsuka/PUCSP-padroes-de-projeto-frameworks
RA 00053113

**Comment by RaphaelPublio** [comment]
**RA00245762 - Raphael Publio**
https://github.com/RaphaelPublio/PUCES-Design-Patterns/wiki/Behavioral
https://github.com/RaphaelPublio/PUCES-Design-Patterns/wiki/Creational
https://github.com/RaphaelPublio/PUCES-Design-Patterns/wiki/Structural

**Comment by leonidassalazar** [comment]
RA00280381
https://github.com/leonidassalazar/PosPuc

**Comment by leticiamrosa** [comment]
RA00273187
https://github.com/leticiamrosa/pucsp-design-patterns
